-- MySQL Script generated by MySQL Workbench
-- Fri Oct  2 13:55:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pet_shop_ib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pet_shop_ib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pet_shop_ib` DEFAULT CHARACTER SET utf8 ;
USE `pet_shop_ib` ;

-- -----------------------------------------------------
-- Table `pet_shop_ib`.`tipo_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`tipo_paciente` (
  `idtipo_paciente` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(100) NOT NULL,
  `porte` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo_paciente`),
  UNIQUE INDEX `idtipo_paciente_UNIQUE` (`idtipo_paciente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`dono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`dono` (
  `iddono` INT NOT NULL AUTO_INCREMENT,
  `nome_dono` VARCHAR(150) NOT NULL,
  `data_nascimento_dono` DATE NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `endereco` TEXT NOT NULL,
  PRIMARY KEY (`iddono`),
  UNIQUE INDEX `iddono_UNIQUE` (`iddono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nome_paciente` VARCHAR(150) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `data_nascimento_paciente` DATE NOT NULL,
  `idtipo_paciente` INT NOT NULL,
  `iddono` INT NOT NULL,
  PRIMARY KEY (`idpaciente`, `idtipo_paciente`, `iddono`),
  UNIQUE INDEX `idpaciente_UNIQUE` (`idpaciente` ASC) VISIBLE,
  INDEX `fk_paciente_tipo_paciente_idx` (`idtipo_paciente` ASC) VISIBLE,
  INDEX `fk_paciente_dono1_idx` (`iddono` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_tipo_paciente`
    FOREIGN KEY (`idtipo_paciente`)
    REFERENCES `pet_shop_ib`.`tipo_paciente` (`idtipo_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_dono1`
    FOREIGN KEY (`iddono`)
    REFERENCES `pet_shop_ib`.`dono` (`iddono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`veterinario` (
  `idveterinario` INT NOT NULL AUTO_INCREMENT,
  `nome_veterinario` VARCHAR(150) NOT NULL,
  `crmv` CHAR(20) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `data_nascimento_veterinario` DATE NOT NULL,
  `endereco_veterinario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idveterinario`),
  UNIQUE INDEX `idveterinario_UNIQUE` (`idveterinario` ASC) VISIBLE,
  UNIQUE INDEX `crmv_UNIQUE` (`crmv` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`consulta` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `data_marcada` DATE NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `motivo` VARCHAR(100) NOT NULL,
  `observacao` TEXT NOT NULL,
  `idpaciente` INT NOT NULL,
  `idveterinario` INT NOT NULL,
  PRIMARY KEY (`idconsulta`, `idpaciente`, `idveterinario`),
  UNIQUE INDEX `idconsulta_UNIQUE` (`idconsulta` ASC) VISIBLE,
  INDEX `fk_consulta_paciente1_idx` (`idpaciente` ASC) VISIBLE,
  INDEX `fk_consulta_veterinario1_idx` (`idveterinario` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `pet_shop_ib`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_veterinario1`
    FOREIGN KEY (`idveterinario`)
    REFERENCES `pet_shop_ib`.`veterinario` (`idveterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(100) NOT NULL,
  `preco_venda` DECIMAL(10,2) NOT NULL,
  `estoque` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idprodutos_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` TIMESTAMP NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `iddono` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `iddono`),
  UNIQUE INDEX `idvenda_UNIQUE` (`idvenda` ASC) VISIBLE,
  INDEX `fk_venda_dono1_idx` (`iddono` ASC) VISIBLE,
  CONSTRAINT `fk_venda_dono1`
    FOREIGN KEY (`iddono`)
    REFERENCES `pet_shop_ib`.`dono` (`iddono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`item_venda` (
  `iditem_venda` INT NOT NULL AUTO_INCREMENT,
  `idvenda` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unidade` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`iditem_venda`, `idvenda`, `idproduto`),
  UNIQUE INDEX `iditem_vedam_UNIQUE` (`iditem_venda` ASC) VISIBLE,
  INDEX `fk_item_venda_venda1_idx` (`idvenda` ASC) VISIBLE,
  INDEX `fk_item_venda_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_item_venda_venda1`
    FOREIGN KEY (`idvenda`)
    REFERENCES `pet_shop_ib`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_venda_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `pet_shop_ib`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet_shop_ib`.`servica_estetica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop_ib`.`servica_estetica` (
  `idservica_estetica` INT NOT NULL AUTO_INCREMENT,
  `data_agendamento` DATETIME NOT NULL,
  `tipo_servico` VARCHAR(50) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `idpaciente` INT NOT NULL,
  PRIMARY KEY (`idservica_estetica`, `idpaciente`),
  UNIQUE INDEX `idservica_estetica_UNIQUE` (`idservica_estetica` ASC) VISIBLE,
  INDEX `fk_servica_estetica_paciente1_idx` (`idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_servica_estetica_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `pet_shop_ib`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;